name: Database Benchmark

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      
    - name: Run benchmark
      run: npx ts-node examples/benchmark-poc.ts
      
    - name: Store benchmark results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark-data/
        retention-days: 90